import Head from 'next/head';
import { useState } from 'react';
import Image from 'next/image';
import { SlideBar, WorkOuts } from './components';
import styles from '../styles/Home.module.css';
import styles2 from '../styles/Pagination.module.css';
const arrayDumby = [
  {
    name: 'Kettle Bell Swing',
    url: 'https://www.youtube.com/watch?v=N-eOdZH7TlU',
  },
  {
    name: 'Push Up',
    url: 'https://www.youtube.com/watch?v=i9sTjhN4Z3M',
  },
  {
    name: 'Jab',
    url: 'https://www.youtube.com/watch?v=euHgMEjZbyU',
  },
  {
    name: 'High Rotational Swings',
    url: 'https://www.youtube.com/watch?v=fLyWq1AOnSs',
  },
  {
    name: 'Lizard Crawl',
    url: 'https://www.youtube.com/watch?v=uknpT9f0lGo',
  },
  {
    name: 'Head Movment',
    url: 'https://www.youtube.com/watch?v=MPSdlbL4Rm0',
  },
];
export default function workOuts() {
  const [currentPage, setcurrentPage] = useState(1);
  const [recordsPerPage] = useState(2);
  const indexOfLastRecord = currentPage * recordsPerPage;
  const indexOfFirstRecord = indexOfLastRecord - recordsPerPage;
  const currentRecords = arrayDumby.slice(
    indexOfFirstRecord,
    indexOfLastRecord
  );
  const nPages = Math.ceil(arrayDumby.length / recordsPerPage);
  const pageNumbers = [...Array(nPages + 1).keys()].slice(1);
  const nextPage = () => {
    if (currentPage !== nPages) setcurrentPage(currentPage + 1);
  };
  const prevPage = () => {
    if (currentPage !== 1) setcurrentPage(currentPage - 1);
  };

  return (
    <>
      <Head>
        <title>10-15</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles2.pageContainer}>
        <ul className={styles2.pageList}>
          <li>
            <a onClick={prevPage} href="#">
              previous
            </a>
          </li>
          {pageNumbers.map((pgNumber) => (
            <li
              key={pgNumber}
              className={`page-item ${
                currentPage == pgNumber ? 'active' : ''
              } `}
            >
              <a onClick={() => setcurrentPage(pgNumber)} href="#">
                {pgNumber}
              </a>
            </li>
          ))}
          <li>
            <a onClick={nextPage} href="#">
              After
            </a>
          </li>
        </ul>

        <WorkOuts name="Routine" arry={currentRecords} />
      </div>
    </>
  );
}
